### ISSUE TITLE
المشكلة في أمر os.listdir 

### ISSUE THREAD

**Issue by waoodejmah** [MohamedMohana/Face-Mask-Detection-Recognition-Using-Colab#1]
تم رفع الـdataset على الدرايف وكل الخطوات الاولى شغاله المشكلة في أمر os.listdir لما يحاول يعرض الصور الموجودة في مسار 'Mask_data/with_mask ' ما يتعرف على الملف الموجود في المسار علما بانه لما اسوي print ل متغير الـpath يعرض المسار 
وايضًا الملفات لما اسوي لها ls و print تظهر بشكل صحيح 
![WhatsApp Image 2022-02-16 at 8 11 36 PM (1)](https://user-images.githubusercontent.com/57574215/154320565-f57f6ba0-e68e-4427-92c0-663b127341f8.jpeg)
![WhatsApp Image 2022-02-16 at 8 11 36 PM](https://user-images.githubusercontent.com/57574215/154320567-91775ff8-b9d9-46b6-a746-c0f199ec08df.jpeg)

**Comment by MohamedMohana** [comment]
بعد تحميل البيانات و فك الضغط ونقلها للدرايڤ يتم تغيير الكود  هنا لمكان الملف
`
DIRECTORY = r"/content/drive/MyDrive/Colab Notebooks/dataset"
`
أنا هنا داخل ملف الـ   Colab Notebooks  أنشأت ملف بإسم dataset ووضعت الداتا بداخله وهي عباره عن ملفين واحد with_mask والأخر withoutmask
