### ISSUE TITLE
Error while executing your program

### ISSUE THREAD

**Issue by JonJoy** [MohamedMohana/Face-Mask-Detection-Recognition-Using-Colab#2]
Hello Sir, while executing the "Start training" part of your program I encountered the following error
![Screenshot (18)](https://user-images.githubusercontent.com/73994985/167641037-f3066622-0929-4016-b6ef-96db7b013355.png)

I'm running the program on google colab as well. Do you know what could be the reason for this error and also may I know what version of tensorflow did you install for this project?

**Comment by JonJoy** [comment]
Hello Sir, while executing the "Start training" part of your program I encountered the following error
![Screenshot (18)](https://user-images.githubusercontent.com/73994985/167641988-c0333687-1a1c-448b-b85d-25a4d3ea6641.png)
I'm running the program on google colab as well. Do you know what could be the reason for this error and also may I know what version of tensorflow did you install for this project?

**Comment by MohamedMohana** [comment]
I ran the code a few days ago and it works perfectly. However, the TF version was the default one in Colab. Your problem seems to happen due to the GPU. Make sure you have change the run time to GPU. In my case, I am using Colab pro.

**Comment by JonJoy** [comment]
Thank you soo much for your reply. I don't know how but it got figured out by itself. Is it possible for me to communicate with you regarding this project on some other media if it isn't of any inconvenience to you?

**Comment by MohamedMohana** [comment]
You are most welcome. I would be really happy to help you here, anytime you want.

**Comment by JonJoy** [comment]
Seems like your program also marks the attendance of students as well right? So if I just want the program to the show the name of the person and whether the person is wearing a mask or not can I omit "def Records" and should I remove the comments in order to show the rectangle around the face with their names?

**Comment by JonJoy** [comment]
Sir, how can I improve the accuracy of the faces being recognized. My dataset contains only 5 images of people in masks and 5 images of the same people without mask. When I run the program people are recognized by a different name. I trained the program with the same Mask_Data as yours. Should I add my dataset as well into the dataset for training?
