### ISSUE TITLE
How can I improve face recognition accuracy

### ISSUE THREAD

**Issue by JonJoy** [MohamedMohana/Face-Mask-Detection-Recognition-Using-Colab#3]
Sir, how can I improve the accuracy of the faces being recognized. My dataset contains only 5 images of people in masks and 5 images of the same people without mask. When I run the program people are recognized by a different name. I trained the program with the same Mask_Data as yours. Should I add my dataset as well into the dataset for training?

_Originally posted by @JonJoy in https://github.com/MohamedMohana/Face-Mask-Detection-and-Recognition/issues/2#issuecomment-1129567755_

**Comment by MohamedMohana** [comment]
Fine images are not enough. Add as much as you can of data.

**Comment by JonJoy** [comment]
Ok thanks

**Comment by JonJoy** [comment]
May I know how many images you used for your dataset? Because now I increased the number of images to 60 total with and without mask but still it isn't accurate.
